# Default initial positions for kr210_arm's ros2_control fake system

initial_positions:
  joint_1: 0
  joint_2: 0
  joint_3: 0
  joint_4: 0
  joint_5: 0
  joint_6: 0
  left_gripper_finger_joint: 0
  right_gripper_finger_joint: 0